name: Test version number

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pypi-simple

    - name: Check version not published
      run: |
        VERSION=$(python setup.py --version)
        if python -c "import pypi_simple; client = pypi_simple.PyPISimple(); versions = [p.version for p in client.get_project_page('pyfolio-performance').packages]; assert '$VERSION' not in versions"; then
          echo "Version $VERSION is not published on PyPI."
        else
          echo "Version $VERSION is already published on PyPI."
          exit 1
        fi