name: Distribute Python Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Create artifact
      run: |
        pip install wheel twine
        python setup.py sdist bdist_wheel
        twine check dist/*

    - name: Authenticate with PyPI
      uses: pypa/gh-action-pypi-publish@v1.5.1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}

    # - name: Upload to PyPI
    #   run: |
    #     python -m twine upload --skip-existing dist/*.whl